<?php
   defined('BASEPATH') OR exit('No direct script access allowed');
   ?>
<div class="main">
   <div class="main-inner">
      <div class="content">
         <div class="faq_header single_page_header has_overlay">
            <div class="header_overlay">
               <div class="container">
                  <h2>Terms &amp; Conditions</h2>
                  <!-- <p>The Process, Step By Step</p> -->
               </div>
            </div>
         </div>
         <div class="single_page_main_content">
            <div class="single_page_section faq_section">
               <div class="container">
                  <div class="faq">
                    <p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">&nbsp;</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><strong><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Terms And Conditions Of Sale And Participation On This Platform.</span></strong></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">1.These terms constitute the entire agreement (&ldquo;Agreement&rdquo;) between Interactive consultants,its defined partners, subsidiaries also using the trademarked name / </span><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">growcrops for the growcropsonline.com platform <span style="font-family: 'Cambria',serif;">(&ldquo;grow crops&rdquo; ) and the purchaser of a farm package (&ldquo;Owner&rdquo;) concerning the farming and sale of the farm produce.</span></span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">1.1. Growcropsonline.com is a platform that enables anyone to own farms we co-manage and supervise cyclical income from sales of crops farmed. As a platform, we simply create a bridge between those ready to farm and finance and get returns from a farm and a farmer anywhere who is ready to provide those services to the person desiring to farm. The models of running the platform via contract farming, direct farming, subsidized farming , subsidized and processing farming* will be totally at growcrops sole discretion. We shall receive and disburse funds from the owner, ensure it is utilized and ensure to the best of our knowledge fair practices is observed on the farm and /or processing system to ensure profitable income while following up on the interested &ldquo;proxy farmer&rdquo; (Owner) to make payment as much as possible as at and when due and ensuring also that either crop produce or the value of the farmed crops are delivered based on predetermined estimates.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">1.2. The Owner agrees to give growcrops absolute discretionary powers as to which means of sale the vegetables or crops would be sold. This will include but not limited to selling as fresh vegetables or processing the vegetables directly or by proxy or via another processing platform which the owner agrees to be transferred with its own favorable terms and conditions with minimum and maximum amounts at growcrops discretion .The overall objective is to help them farm and get returns from the farm produce.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">1.3. The owner agrees that where perishable produce exist, effort is made to mitigate the losses and not transfer such losses to the owner. Where processing is required, the owner agrees for growcrops to process on its behalf with the aim that income or product is delivered to the owner.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">2.This Agreement shall become effective on the date on which the Owner purchases or books a farm package from grow crops, subject to i) the Owner making payment of the price in instalments or (ii) the Owner paying the price in full.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">3.The Owner purchases a farm package from grow crops. The Owner shall have limited rights of ownership in the leased farm. All rights shall remain with grow crops for proper management. The rights of the owner is limited to the final crops output for four months OR any processed products that can cumulatively be valued at the cost of income from such crops for four months.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">3.1 grow crops shall retain the sole and exclusive right to give, carry out all the instructions and receive payments and&nbsp; on behalf of the Owner, which it shall exercise in accordance with the terms of this Agreement;</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">3.2 grow crops shall retain the sole and exclusive right to knowledge as to how the farm is run and managed;</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">3.3 grow crops shall be the sole and exclusive provider of farming services (&ldquo;Farming Services&rdquo;) to the client and his farm.</span></p>
<ol start="4">
<li style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;"><span style="font-family: 'Cambria',serif;">The price of the produce shall be the prevailing market price at the time of purchase or as deemed fit by growcropsonline due to market realities and the desire to make a sale.</span></span></li>
<li style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;"> A farm package may be purchased by pre-payment on back-order in the event that delivery of farm package is not possible at the time of purchase. In that event this Agreement will become effective on date of the subsequent purchase, and the price of the package will be fixed at that date. grow crops obligation to perform under this Agreement will in that case become effective on date of presentation/ sending of farm certificate. grow crops will endeavour to fulfil a purchase on back-order within four months of payment.</span></li>
</ol>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">5.1. In growcrops executing this its duties under this agreement however, timing shall not be of the essence to PERFORMING this Agreement and the delivery time period is not guaranteed. The owner however is bound by time determined by growcrops.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">6.grow crops shall provide Farming Services on behalf of the Owner. Farming Services shall also be rendered on the farm. Farming Services shall be constituted as lease of land, purchase of inputs, labour for all stages from planting to harvest, processing then sell or sell outright. The delays in payment for these services attract penalty sums as determined by growcrops.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">6.1 Farm rental in historically productive crop areas documentation knowledge and details of which shall be the exclusive possession of grow crops. Lease of land confers no title or rights to the owner but shall enable the farmer the opportunity to partake in any of the existing schemes with crops and the entry will be evidenced with a certificate or receipt which shall be sent to the owner as acceptance of access into a part of any of the transactions; without the certificate, no transaction can commence.&nbsp;</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">6.2 The maintenance of the farm in a good, productive and healthy condition in a farm co-operated by grow crops while also ensuring that regardless of where land is located, should any issues arise on those owner selected areas, grow crops has a discretion to put in place an immediate substitute in a location convenient enough for grow crops to deliver what was offered;</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">6.5 The use of measurement being Hectares with &nbsp;the definition of Hectares shall not necessarily construe the TRUE meaning of hectares but shall be interpreted as one PORTION OF LAND WITH AN ATTACHED estimated income. The owner agrees that regardless of whether it is an acre or two acres, hectares does NOT&nbsp;necessarily mean TWO AND A HALF ACRES OF LAND. Hectares is simply described as a unit of measurement.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">6.6 The probable operation of a reporting system that enables the Owner to remotely view the farm or know updates of what is going on in the farms at a future date could be implemented at a system and cost to be determined by growcrops </span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">6.7 The provision of urgent services in cases of emergency.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">6.8&nbsp; Farming services shall be payable periodically or monthly in advance via debit order or bank transfer by whatever means.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">6.9 The farming invoice may be emailed to the Owner periodically.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">7.The Owner agrees that grow crops will provide Farming Services to the Owner&rsquo;s farm on an accredited grow crops farm in terms of this Agreement until the farm harvest period , and that this Agreement may renew thereafter if a cycle exists and payment is made.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">&nbsp;8.When the harvest is ready, grow crops shall and is authorized to:</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">8.1 Deliver the produce to the Owner or Sell the produce on behalf of the Owner at the prevailing market price or at a price </span><span style="font-size: 12.0pt; font-family: 'Cambria',serif;"><a href="http://growcropsonline.com">growcropsonline.com</a><span style="font-family: 'Cambria',serif;"> chooses to sell the crop to close a sale and ensure there are no losses; and</span></span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">8.2 Apply the proceeds of the sale to Whatever the owner directs.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">9.grow crops shall then provide Farming Services to the Owner in accordance with this Agreement. The parties agree that this cycle will continue and repeat itself subject to (7) above.</span></p>
<ol start="10">
<li style="margin-bottom: 11.25pt; margin-left: 18.0pt; text-align: justify; text-indent: -22.5pt; tab-stops: list 18.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">If there is a shortfall in meeting the cost of replacement of crops after insurance issues, grow crops shall make provision for the shortfall at no extra charge to the Owner.</span>
<ul>
<li style="margin-bottom: 11.25pt; margin-left: 22.5pt; text-align: justify; text-indent: -27.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">When a farm has produce for harvest, grow crops shall and is authorised to:</span></li>
</ul>
</li>
</ol>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">11.1 Apply the proceeds of the sale communally, together with the proceeds of all other Individual subscriptions on a grow crops farm in a given year, to the meeting of the costs to the Owner and the other owners of farms on the grow crops farm in the same year; and</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">11.2 Pay out to the Owner and the other owners of farms on the grow crops farm shall be according to the size of farms they own. Both farm owner and subscriber having full knowledge that anything over a ma</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">ximum of 30% profit is a very good payout although growcropsonline shall strive to achieve regardless of the information on the site is higher than both the maximum 50% and what exists on the site.</span></p>
<ol start="12">
<li style="margin-bottom: 11.25pt; margin-left: 13.5pt; text-align: justify; text-indent: -18.0pt; tab-stops: list 13.5pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The Income is a financial return to the Owner that comes from the income earned from crop sales. Grow crops provides Farming Services on behalf of the Owner until harvest. Thereafter the subsequent farming season would have a new payment terms based on percentage and set targets.</span></li>
<li style="margin-bottom: 11.25pt; margin-left: 13.5pt; text-align: justify; text-indent: -18.0pt; tab-stops: list 13.5pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">In the event that the Owner&rsquo;s farm does not perform as projected or, in the discretion of grow crops exercised in the best interests of the performance of this Agreement, it stands to be replaced and proceeds sold, then grow crops shall and is authorized to:</span></li>
</ol>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">13.1 Sell the produce at the Owners instruction on behalf of the Owner, and</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">13.2 Apply the proceeds of the sale to whatever the Owner directs .</span></p>
<ol>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">grow crops shall not be liable to the Owner for any losses or damages suffered by the Owner in the event that the farm doesn&rsquo;t produce as expected after all NECESSARY processes and procedures have been utilized according to its fair practices. Whatever measures used to cause a replacement at the discretion of grow crops will be exercised in the best interests of the performance of this Agreement, unless the cause for such circumstance is the intentional or negligent conduct of grow crops or its employees or contractors.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">grow crops and the Owner agree that grow crops has no obligation and shall not be required to produce any receipts of payment,individual or general proof of expenditure, evidence of how money was spent and any related or associated account rendering with evidence purposes. Both parties agree that the invoice and details in the invoice remain the only form of account per render that is required.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The relationship between growcrops and the owner shall be that of independent contractors and not principal and agent.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">grow crops will however assist in obtaining requisite insurance cover for the farming process, the final crops are not insured for any risks.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The Owner is not entitled to terminate this Agreement before harvest time.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Any termination before harvest time is deemed as abandonment of all your rights and funds previously paid. Abandonment shall also include meaning non payment after 10 days of invoiced sum with penalties or after TWO correspondences indicating reminder of lack of payment of invoice. </span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">grow crops shall have a lien (i.e. right of retention) over the farm and its produce until all amounts owed by the Owner to grow crops in terms of this Agreement, including but not limited to all unrecovered Farming Services costs, bank charges and usual administrative expenses, are paid in full.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">In the event that the Owner terminates this Agreement before the first harvest, grow crops by the terms of this Agreement, shall not be liable for any refunds and shall use whatever remaining interest or crops to be reimbursed for services including but not limited to all unrecovered Farming Services costs, bank charges and usual administrative expenses.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The Owner shall not use the farm or its produce as collateral or security for any transaction, or sell or dispose of interest in the farm or any of the Owner&rsquo;s rights therein without first obtaining the written approval of grow crops.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">In the event that the Owner would like to visit the grow crops farm to view the farm, a prior appointment with grow crops shall be made on reasonable notice as determined by growcropsonline and specific circumstances.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The interest earned on all monies held by grow crops on behalf of the Owner in terms of this Agreement shall accrue to grow crops.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">If either of the parties breach any provision of this Agreement &nbsp;like sending of certificates, non payment of invoiced sums etc and specifically exempting anything related to the issue of amounts to be paid from income from the farm at a specific time (&ldquo;Defaulting Party&rdquo;) and, if such breach is capable of being remedied, fails to remedy the breach within 10 days after written notice has been given to the Defaulting Party by the other party requiring the breach to be remedied (&ldquo;Aggrieved Party&rdquo;), the Aggrieved Party shall be entitled, without prejudice to any other rights it may have, to:</span></li>
</ol>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">22.1 Seek an order for specific performance against the Defaulting Party; or</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">22.2 To claim any damages suffered by the Aggrieved Party.</span></p>
<ol>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The Owner shall be liable for all costs and expenses (calculated on an attorney and own client scale) incurred as a result of or in connection with any breach.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">This Agreement shall in all respects (including its existence, validity, interpretation, implementation, termination and enforcement) be governed by the law of Nigeria and limits this agreement to a commercial transaction.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">This Agreement constitutes the whole agreement between the parties relating to the subject matter hereof and supersedes all other discussions, agreements and/or understandings regarding the subject matter hereof.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">No amendment or consensual cancellation of this Agreement or any provision hereof, and no settlement of any disputes arising out of this Agreement, and no extension of time, waiver or relaxation or suspension of or agreement not to enforce or to suspend or postpone the enforcement of any of the provisions of this Agreement, shall be binding unless first recorded in writing and signed by the parties .</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">As such by this agreement, no disputes arising out of this Agreement, and no extension of time, waiver or relaxation or suspension of or agreement shall be connoted as fraud as long as the owner is given an opportunity to visit his or her farm and announces such on instagram or via email. Both parties agree that any connotation or implied statements to that effect breaches this agreement directly.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">To the extent permissible by law, no party shall be bound by any express or implied or tacit term, representation, warranty, promise or the like not recorded herein, whether it induced the contract and/or whether it was negligent or not.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Any provision in this Agreement which is or may become illegal, invalid or unenforceable, shall be ineffective to the extent of such prohibition or unenforceability and shall be treated as if it had not been drafted and severed from the balance of this Agreement, without invalidating the remaining provisions of this Agreement.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">This Agreement shall be binding on both parties only.</span></li>
<li style="margin-bottom: 11.25pt; text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The rights and obligations of the Owner in terms of this Agreement may not be ceded or assigned without the prior written permission of grow crops.</span></li>
</ol>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Use of Site</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">You may only use this site to browse the content, make legitimate purchases and shall not use this site for any other purposes, including without limitation, to make any speculative, false or fraudulent purchase. This site and the content provided in this site may not be copied, reproduced, republished, uploaded, posted, transmitted or distributed. 'Deep-linking', 'embedding' or using analogous technology is strictly prohibited. Unauthorized use of this site and/or the materials contained on this site may violate applicable copyright, trademark or other intellectual property laws or other laws.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Disclaimer of Warranty</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The contents of this site are provided "as is" without warranty of any kind, either expressed or implied, including but not limited to warranties of merchantability, fitness for a purpose and non-infringement.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The owner of this site, the authors of these contents and in general anybody connected to this site in any way, from now on collectively called "Providers", assume no responsibility for errors or omissions in these contents and expressly state that "own " farm" as a term means or must be interpreted as being a part of a project and be entitled to some form of pay out at the end.&nbsp;</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The Providers further do not warrant, guarantee or make any representation regarding the safety, reliability, accuracy, correctness or completeness of these contents. The Providers shall not be liable for any direct, indirect, general, special, incidental or consequential damages (including -without limitation- data loss, lost revenues and lost profit) which may result from the inability to use or the correct or incorrect use, abuse, or misuse of these contents, even if the Providers have been informed of the possibilities of such damages. The Providers cannot assume any obligation or responsibility.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The use of these contents is forbidden in those places where the law does not allow this disclaimer to take full effect.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Our Rights</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">We reserve the right to:</span></p>
<ul>
<li style="text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Modify or withdraw, temporarily or permanently, the Website (or any part of) with or without notice to you and you confirm that we shall not be liable to you or any third party for any modification to or withdrawal of the Website; and/or</span><span style="font-size: 12.0pt; font-family: 'Cambria',serif;"> </span><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">2. Change these Conditions from time to time, and your use of the Website (or any part of) following such change shall be deemed to be your acceptance of such change. It is your responsibility to check regularly to determine whether the Conditions have been changed. If you do not agree to any change to the Conditions then you must immediately stop using the Website. 3. We will use our reasonable endeavours to maintain the Website. The Website is subject to change from time to time. You will not be eligible for any compensation because you cannot use any part of the Website or because of a failure, suspension or withdrawal of all or part of the Website due to circumstances beyond our control.</span></li>
</ul>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Privacy Policy</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">We are committed to protecting your privacy. This privacy policy applies to all the web pages related to this website.  All the information gathered in the online forms on the website is used to personally identify users that subscribe to this service. The information will not be used for anything other that which is stated in the Terms &amp; Conditions of use for this service. None of the information will be sold or made available to anyone.  The Site may collect certain information about your visit, such as the name of the Internet service provider and the Internet Protocol (IP) address through which you access the Internet; the date and time you access the Site; the pages that you access while at the Site and the Internet address of the Web site from which you linked directly to our site. These information are used to help improve the Site, analyze trends, and administer the Site.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">We may need to change this policy from time to time in order to address new issues and reflect changes on our site. We will post those changes here so that you will always know what information we gather, how we might use that information, and whether we will disclose that information to anyone. Please refer back to this policy regularly. If you have any questions or concerns about our privacy policy, please send us an E-mail.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">By using this website, you signify your acceptance of our Privacy Policy. If you do not agree to this policy, please do not use our site. Your continued use of the website following the posting of changes to these terms will mean that you accept those changes.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Cookie/Tracking Technology</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The Site may use cookie and tracking technology depending on the features offered. Cookie and tracking technology are useful for gathering information such as browser type and operating system, tracking the number of visitors to the Site, and understanding how visitors use the Site. Cookies can also help customize the Site for visitors. Personal information cannot be collected via cookies and other tracking technology; however, if you previously provided personally identifiable information, cookies may be tied to such information. Aggregate cookie and tracking information may be shared with third parties.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Third Party Links</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">In an attempt to provide increased value to our Users, we may provide links to other websites or resources. You acknowledge and agree that we are not responsible for the availability of such external sites or resources, and do not endorse and are not responsible or liable, directly or indirectly, for the privacy practices or the content (including misrepresentative or defamatory content) of such websites, including (without limitation) any advertisement, products or other materials or services on or available from such websites or resources, nor for any damage, loss or offence caused or alleged to be caused by, or in connection with, the use of or reliance on any such content, goods or services available on such external sites or resources.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">&nbsp; For more information about how to invest, special order requirements and other payment options, please contact our Support Team on the contact number on the website or send us an email HERE</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Security Policy</span></p>
<ul>
<li style="text-align: justify; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The merchant has no access to debit or credit card details nor is the merchant responsible for any errors relating to card security generally and specifically on this site</span></li>
</ul>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Monitoring</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">We have the right, but not the obligation, to monitor any activity and content associated with the Website. We may investigate any reported violation of these Conditions or complaints and take any action that we deem appropriate (which may include, but is not limited to, issuing warnings, suspending, terminating or attaching conditions to your access and/or removing any materials from the Website).</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Law</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">The Conditions will be exclusively governed by and construed in accordance with the laws of Nigeria whose Courts will have exclusive jurisdiction in any dispute, save that we have the right, at our sole discretion, to commence and pursue proceedings in alternative jurisdictions.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Updating of these Terms and Conditions</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">We reserve the right to change, modify, add to or remove from portions or the whole of these Terms and Conditions from time to time. Changes to these Terms and Conditions will become effective upon such changes being posted to this Website. It is the User&rsquo;s obligation to periodically check these Terms and Conditions at the Website for changes or updates. The User&rsquo;s acceptance of these terms will be considered notice of the User&rsquo;s acceptance to abide by and be bound by these Terms and Conditions, including all such changes or updates.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Force Majeure.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">In no event shall growcrops be responsible or liable for any failure or delay in the performance of its obligations hereunder arising out of or caused by, directly or indirectly, forces beyond its control, including, without limitation, strikes, work stoppages, accidents, acts of war or terrorism, civil or military disturbances, nuclear or natural catastrophes or acts of God, and interruptions, loss or malfunctions of utilities, lack of sales, communications or computer (software and hardware) services; it being understood that growcrops shall use reasonable efforts to resume performance as soon as practicable under the circumstances and where it is not possible, growcrops shall be liable to pay the minimum of the sum given to it back within minimum of TWO YEARS or provide either processed crops/ products which have been processed in addition with the crops or any other products produced for or by growcrops within the same time line. Growcrops will be required to publicly announce a force majeure and shall be further required however to write and inform the owner of the force majeure, explain the circumstances and inform the owner immediately what the recourse would be in that event. The owner agrees to be bound by the remedy terms as long as a minimum of the owners invested sum is reimbursed or products worth its value is delivered to the owner within the minimum two year time frame.</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">Consent</span></p>
<p style="text-align: justify; line-height: 21.0pt; margin: 0cm 0cm 7.5pt 0cm;"><span style="font-size: 12.0pt; font-family: 'Cambria',serif;">I&nbsp;understand that all the designs and trademarks&nbsp;are registered&nbsp;to </span><span style="font-size: 12.0pt; font-family: 'Cambria',serif;"><a href="http://growcropsonline.com">growcropsonline.com</a><span style="font-family: 'Cambria',serif;"> and interactive consultants and hereby accept&nbsp;the terms and conditions. I undertake not to copy/duplicate the trademarks and designs&nbsp;directly or indirectly in anyway and understand the legal implications thereof. Should I be found to be in violation of this agreement I understand that I will be held liable for all legal costs incurred by </span><a href="http://growcropsonline.com">growcropsonline.com</a><span style="font-family: 'Cambria',serif;"> and interactive consultants for any civil or any&nbsp;legal action.</span></span></p>
                  </div>
                  <!-- /.faq -->
               </div>
            </div>
         </div>
      </div>
      <!-- /.content -->
   </div>
   <!-- /.main-inner -->
</div>
